# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sem_seg_server.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sem_seg_server.proto',
  package='sem_seg_server',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x14sem_seg_server.proto\x12\x0esem_seg_server\"\x9d\x01\n\x0fSegmentedObject\x12\r\n\x05label\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x02\x12\x0c\n\x04\x61rea\x18\x03 \x01(\x02\x12:\n\x08\x63\x65ntroid\x18\x04 \x01(\x0b\x32(.sem_seg_server.SegmentedObject.Centroid\x1a\"\n\x08\x43\x65ntroid\x12\n\n\x02\x63x\x18\x01 \x01(\x02\x12\n\n\x02\x63y\x18\x02 \x01(\x02\"D\n\x13SegmentedObjectData\x12-\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1f.sem_seg_server.SegmentedObject\"1\n\x10\x43\x61meraResolution\x12\r\n\x05width\x18\x01 \x01(\x05\x12\x0e\n\x06height\x18\x02 \x01(\x05\"\x07\n\x05\x45mpty2\xbd\x01\n\x14SemanticSegmentation\x12S\n\x13GetSegmentedObjects\x12\x15.sem_seg_server.Empty\x1a#.sem_seg_server.SegmentedObjectData\"\x00\x12P\n\x13GetCameraResolution\x12\x15.sem_seg_server.Empty\x1a .sem_seg_server.CameraResolution\"\x00\x62\x06proto3'
)




_SEGMENTEDOBJECT_CENTROID = _descriptor.Descriptor(
  name='Centroid',
  full_name='sem_seg_server.SegmentedObject.Centroid',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cx', full_name='sem_seg_server.SegmentedObject.Centroid.cx', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cy', full_name='sem_seg_server.SegmentedObject.Centroid.cy', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=164,
  serialized_end=198,
)

_SEGMENTEDOBJECT = _descriptor.Descriptor(
  name='SegmentedObject',
  full_name='sem_seg_server.SegmentedObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='label', full_name='sem_seg_server.SegmentedObject.label', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='sem_seg_server.SegmentedObject.score', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='area', full_name='sem_seg_server.SegmentedObject.area', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='centroid', full_name='sem_seg_server.SegmentedObject.centroid', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[_SEGMENTEDOBJECT_CENTROID, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=198,
)


_SEGMENTEDOBJECTDATA = _descriptor.Descriptor(
  name='SegmentedObjectData',
  full_name='sem_seg_server.SegmentedObjectData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='data', full_name='sem_seg_server.SegmentedObjectData.data', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=200,
  serialized_end=268,
)


_CAMERARESOLUTION = _descriptor.Descriptor(
  name='CameraResolution',
  full_name='sem_seg_server.CameraResolution',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='sem_seg_server.CameraResolution.width', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='height', full_name='sem_seg_server.CameraResolution.height', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=270,
  serialized_end=319,
)


_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='sem_seg_server.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=321,
  serialized_end=328,
)

_SEGMENTEDOBJECT_CENTROID.containing_type = _SEGMENTEDOBJECT
_SEGMENTEDOBJECT.fields_by_name['centroid'].message_type = _SEGMENTEDOBJECT_CENTROID
_SEGMENTEDOBJECTDATA.fields_by_name['data'].message_type = _SEGMENTEDOBJECT
DESCRIPTOR.message_types_by_name['SegmentedObject'] = _SEGMENTEDOBJECT
DESCRIPTOR.message_types_by_name['SegmentedObjectData'] = _SEGMENTEDOBJECTDATA
DESCRIPTOR.message_types_by_name['CameraResolution'] = _CAMERARESOLUTION
DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SegmentedObject = _reflection.GeneratedProtocolMessageType('SegmentedObject', (_message.Message,), {

  'Centroid' : _reflection.GeneratedProtocolMessageType('Centroid', (_message.Message,), {
    'DESCRIPTOR' : _SEGMENTEDOBJECT_CENTROID,
    '__module__' : 'sem_seg_server_pb2'
    # @@protoc_insertion_point(class_scope:sem_seg_server.SegmentedObject.Centroid)
    })
  ,
  'DESCRIPTOR' : _SEGMENTEDOBJECT,
  '__module__' : 'sem_seg_server_pb2'
  # @@protoc_insertion_point(class_scope:sem_seg_server.SegmentedObject)
  })
_sym_db.RegisterMessage(SegmentedObject)
_sym_db.RegisterMessage(SegmentedObject.Centroid)

SegmentedObjectData = _reflection.GeneratedProtocolMessageType('SegmentedObjectData', (_message.Message,), {
  'DESCRIPTOR' : _SEGMENTEDOBJECTDATA,
  '__module__' : 'sem_seg_server_pb2'
  # @@protoc_insertion_point(class_scope:sem_seg_server.SegmentedObjectData)
  })
_sym_db.RegisterMessage(SegmentedObjectData)

CameraResolution = _reflection.GeneratedProtocolMessageType('CameraResolution', (_message.Message,), {
  'DESCRIPTOR' : _CAMERARESOLUTION,
  '__module__' : 'sem_seg_server_pb2'
  # @@protoc_insertion_point(class_scope:sem_seg_server.CameraResolution)
  })
_sym_db.RegisterMessage(CameraResolution)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'sem_seg_server_pb2'
  # @@protoc_insertion_point(class_scope:sem_seg_server.Empty)
  })
_sym_db.RegisterMessage(Empty)



_SEMANTICSEGMENTATION = _descriptor.ServiceDescriptor(
  name='SemanticSegmentation',
  full_name='sem_seg_server.SemanticSegmentation',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=331,
  serialized_end=520,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetSegmentedObjects',
    full_name='sem_seg_server.SemanticSegmentation.GetSegmentedObjects',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_SEGMENTEDOBJECTDATA,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='GetCameraResolution',
    full_name='sem_seg_server.SemanticSegmentation.GetCameraResolution',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_CAMERARESOLUTION,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_SEMANTICSEGMENTATION)

DESCRIPTOR.services_by_name['SemanticSegmentation'] = _SEMANTICSEGMENTATION

# @@protoc_insertion_point(module_scope)
